### ISSUE TITLE
Альтернативное действие кнопки Play

### ISSUE THREAD

**Issue by dkrnl** [nuklea/chromus#1]
Кпопка play -- та которая добавляет у каждого трека на last.fm
Хотелось бы альтернативное действие -- добавлять трек к текущему листу, а не перетирать соседними треками (как сейчас). 

Варианты реализации:
1. right click - без коментариев
2. checkbox - в нижнем тулбаре "append tracks in list".
3. еще одна кнопка с иконкой плюс

что лучше/быстрее/проще -- не знаю (:

**Comment by nuklea** [comment]
Мне нравится вариант с плюсиком. Но не хочется разгомождать список треков левыми контролами. Да и вставка в дерево будет еще больше тупить. Думаю насчет малюсенького всплывающего меню.

**Comment by dkrnl** [comment]
куку
